# Настройки сохранения (RDB) - снимок каждые:
#   600 секунд, если ≥1 изменений
#   300 секунд, если ≥10 изменений
#   60 секунд, если ≥10000 изменений
save 600 1
save 300 10
save 60 10000

# Файл снимка и папка данных
dbfilename dump.rdb
dir /data
