"""
Revision ID: 01a72d5c2d3e
Revises: 925a195d4144
Create Date: 2025-06-24 16:47:40.027591

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import uuid
from app.core.utils import hash_password

# revision identifiers, used by Alembic.
revision: str = "01a72d5c2d3e"
down_revision: Union[str, None] = "925a195d4144"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "super_user",
        sa.Column("login", sa.String(length=150), nullable=False),
        sa.Column("password", sa.String(length=150), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_super_user")),
    )
    # ### end Alembic commands ###

    # Insert default super user with hashed password
    default_id = uuid.uuid4()  # Pass a UUID object, not string
    default_login = "parrylingo_admin"
    default_password = hash_password("stringst")

    conn = op.get_bind()
    conn.execute(
        sa.text(
            "INSERT INTO super_user (id, login, password) VALUES (:id, :login, :password)"
        ),
        {"id": default_id, "login": default_login, "password": default_password},
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("super_user")
    # ### end Alembic commands ###
