"""

Revision ID: 0d108e54907c
Revises: 7bd2b7816705
Create Date: 2025-07-31 12:23:15.346503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "0d108e54907c"
down_revision: Union[str, None] = "7bd2b7816705"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_lesson_language_id_language"), "lesson", type_="foreignkey"
    )
    op.drop_column("lesson", "language_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lesson",
        sa.Column("language_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_lesson_language_id_language"),
        "lesson",
        "language",
        ["language_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
