"""

Revision ID: 42a479675515
Revises: d95e1f2b878c
Create Date: 2025-07-24 18:43:30.132233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "42a479675515"
down_revision: Union[str, None] = "d95e1f2b878c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем временную колонку
    op.add_column(
        "word",
        sa.Column(
            "audio_url_tmp", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )

    # 2. Переносим данные из VARCHAR в JSONB через SQL
    op.execute(
        """
        UPDATE word w
        SET audio_url_tmp = jsonb_build_object(lang.language_code, w.audio_url)
        FROM lesson l
        JOIN language lang ON l.language_id = lang.id
        WHERE w.lesson_id = l.id;
    """
    )

    # 3. Удаляем старую колонку
    op.drop_column("word", "audio_url")

    # 4. Переименовываем временную колонку в основную
    op.alter_column(
        "word",
        "audio_url_tmp",
        new_column_name="audio_url",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "word",
        "audio_url",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
