"""

Revision ID: 55fa062a8c54
Revises: 746d1c429b46
Create Date: 2025-05-30 17:13:22.024662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "55fa062a8c54"
down_revision: Union[str, None] = "746d1c429b46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.String(length=150), nullable=False))
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "first_name",
            sa.VARCHAR(length=150),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "last_name",
            sa.VARCHAR(length=150),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user", "name")
    # ### end Alembic commands ###
