"""

Revision ID: 6733a106a49b
Revises: 2ce1e2d47fc7
Create Date: 2025-07-09 16:37:03.275068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "6733a106a49b"
down_revision: Union[str, None] = "2ce1e2d47fc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_block", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_block")
    # ### end Alembic commands ###
