"""add media_missing to word

Revision ID: 7a1a00b8c992
Revises: 0d108e54907c
Create Date: 2026-02-20 11:42:03.979889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "7a1a00b8c992"
down_revision: Union[str, None] = "0d108e54907c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_interface_language_code_language"),
        "interface",
        "language",
        ["language_code"],
        ["language_code"],
    )
    op.create_foreign_key(
        op.f("fk_language_language_code_interface"),
        "language",
        "interface",
        ["language_code"],
        ["language_code"],
    )
    op.add_column(
        "word", sa.Column("media_missing", sa.Boolean(), default=False, nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("word", "media_missing")
    op.drop_constraint(
        op.f("fk_language_language_code_interface"),
        "language",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_interface_language_code_language"),
        "interface",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
