"""

Revision ID: 7bd2b7816705
Revises: a0da468e54e9
Create Date: 2025-07-31 11:27:38.580706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "7bd2b7816705"
down_revision: Union[str, None] = "a0da468e54e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "topic",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "updated_at")
    op.drop_column("topic", "created_at")
    # ### end Alembic commands ###
