"""

Revision ID: 925a195d4144
Revises: c4c0955fc27f
Create Date: 2025-06-22 21:09:07.424102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "925a195d4144"
down_revision: Union[str, None] = "c4c0955fc27f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "avatar",
        sa.Column("link", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_avatar")),
    )
    op.create_unique_constraint(
        op.f("uq_interface_language_code"), "interface", ["language_code"]
    )
    op.add_column("user", sa.Column("email", sa.String(length=150), nullable=True))
    op.add_column("user", sa.Column("password", sa.String(length=150), nullable=True))
    op.add_column("user", sa.Column("avatar_id", sa.UUID(), nullable=True))
    op.add_column("user", sa.Column("total_stars", sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f("uq_user_email"), "user", ["email"])
    op.create_foreign_key(
        op.f("fk_user_avatar_id_avatar"),
        "user",
        "avatar",
        ["avatar_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_user_avatar_id_avatar"), "user", type_="foreignkey")
    op.drop_constraint(op.f("uq_user_email"), "user", type_="unique")
    op.drop_column("user", "total_stars")
    op.drop_column("user", "avatar_id")
    op.drop_column("user", "password")
    op.drop_column("user", "email")
    op.drop_constraint(op.f("uq_interface_language_code"), "interface", type_="unique")
    op.drop_table("avatar")
    # ### end Alembic commands ###
