"""

Revision ID: a0da468e54e9
Revises: 42a479675515
Create Date: 2025-07-30 16:55:16.183156

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a0da468e54e9"
down_revision: Union[str, None] = "42a479675515"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic",
        sa.Column("names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic")),
    )
    op.add_column("lesson", sa.Column("topic_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_lesson_topic_id_topic"),
        "lesson",
        "topic",
        ["topic_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_lesson_topic_id_topic"), "lesson", type_="foreignkey")
    op.drop_column("lesson", "topic_id")
    op.drop_table("topic")
    # ### end Alembic commands ###
