"""

Revision ID: c4c0955fc27f
Revises: 56df8ed2e1ff
Create Date: 2025-06-05 19:37:28.170553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4c0955fc27f"
down_revision: Union[str, None] = "56df8ed2e1ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interface",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("language_code", sa.String(), nullable=False),
        sa.Column("flag_code", sa.String(), nullable=False),
        sa.Column(
            "interface",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("language_code", name=op.f("pk_interface")),
        sa.UniqueConstraint("language_code", name=op.f("uq_interface_language_code")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interface")
    # ### end Alembic commands ###
