"""

Revision ID: d95e1f2b878c
Revises: 6733a106a49b
Create Date: 2025-07-24 17:14:35.577706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "d95e1f2b878c"
down_revision: Union[str, None] = "6733a106a49b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_lesson_roulette_progress",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("language_id", sa.UUID(), nullable=True),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language.id"],
            name=op.f("fk_user_lesson_roulette_progress_language_id_language"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_lesson_roulette_progress_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_lesson_roulette_progress")),
    )
    op.add_column(
        "user_lesson_progress",
        sa.Column("language_id", sa.UUID(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_user_lesson_progress_language_id_language"),
        "user_lesson_progress",
        "language",
        ["language_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_lesson_progress_language_id_language"),
        "user_lesson_progress",
        type_="foreignkey",
    )
    op.drop_column("user_lesson_progress", "language_id")
    op.drop_table("user_lesson_roulette_progress")
    # ### end Alembic commands ###
