"""

Revision ID: e0d7d085549f
Revises: 01a72d5c2d3e
Create Date: 2025-06-26 16:21:00.271041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "e0d7d085549f"
down_revision: Union[str, None] = "01a72d5c2d3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "avatar",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "avatar",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("avatar", "updated_at")
    op.drop_column("avatar", "created_at")
    # ### end Alembic commands ###
